@startuml
'https://plantuml.com/class-diagram

interface DocumentWriter
interface VectorStore
class FileDocumentWriter


DocumentWriter <|-- FileDocumentWriter
DocumentWriter <|- VectorStore
VectorStore <|-- ChromaVectorStore
VectorStore <|-- MilvusVectorStore
VectorStore <|-- MariaDBVectorStore
VectorStore <|-- ElasticsearchVectorStore
VectorStore <|-- MongoDBAtlasVectorStore
VectorStore <|-- Neo4jVectorStore
VectorStore <|-- RedisVectorStore
VectorStore <|-- 其它

@enduml