@startuml mcp_flow
skinparam usecaseFontSize 14
skinparam usecaseStereotypeFontSize 12
skinparam hexagonFontSize 14
skinparam hexagonStereotypeFontSize 12
title "mcp flow"
footer

powered by spring-ai-alibaba
end footer
circle start<<input>> as __START__
circle stop as __END__
usecase "mcp"<<Node>>
"__START__" -down-> "mcp"
"mcp" -down-> "__END__"
@enduml