@startuml
'https://plantuml.com/class-diagram

interface Evaluator
class RelevancyEvaluator
class FactCheckingEvaluator

Evaluator <|-- RelevancyEvaluator
Evaluator <|-- FactCheckingEvaluator



@enduml