@startuml
'https://plantuml.com/class-diagram

interface QueryTransformer

QueryTransformer <|-- CompressionQueryTransformer
QueryTransformer <|-- RewriteQueryTransformer
QueryTransformer <|-- TranslationQueryTransformer


@enduml