@startuml
'https://plantuml.com/class-diagram


interface Advisor
interface CallAdvisor
interface StreamAdvisor
interface BaseAdvisor
interface BaseChatMemoryAdvisor
class ChatModelCallAdvisor


Advisor <|-- CallAdvisor
Advisor <|-- StreamAdvisor
CallAdvisor <|-- BaseAdvisor
StreamAdvisor <|-- BaseAdvisor
BaseAdvisor <|-- BaseChatMemoryAdvisor
CallAdvisor <|-- ChatModelCallAdvisor
StreamAdvisor <|-- ChatModelStreamAdvisor
BaseChatMemoryAdvisor <|-- MessageChatMemoryAdvisor
BaseChatMemoryAdvisor <|-- PromptChatMemoryAdvisor
BaseChatMemoryAdvisor <|-- VectorStoreChatMemoryAdvisor
BaseAdvisor <|-- QuestionAnswerAdvisor

@enduml